### ISSUE TITLE
Can't execute commands

### ISSUE THREAD

**Issue by a455455b** [CatchZeng/AppThinning#1]
const { getIgnoredFiles, appendIgnoreFiles } = require("./src/ingore/index");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by CatchZeng** [comment]
node 版本是多少的？
node -v

根据README，一步步操作了吗？

**Comment by a455455b** [comment]
node -v
v4.5.0
剩下的都按照readMe来的

**Comment by CatchZeng** [comment]
node 升级下，我记得是 6.x 以上才支持新的语法，最好安装个 8.x 的

**Comment by a455455b** [comment]
好嘞
